config/routes.rb
Biblio::Application.routes.draw do
  devise_for :users

  resources :books
  root :to => 'books#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/book.rb
require 'goodreads'

class Book < ActiveRecord::Base
  # validates :author, :title, :isbn, presence: true

  attr_accessible :author, :isbn, :title, :avatar
  mount_uploader :avatar, AvatarUploader

  before_create :isbn_lookup 
  

  belongs_to :user

  def isbn_lookup
      if self.isbn
        client = Goodreads::Client.new(:api_key => ENV["GOODREADS_KEY"], :api_secret => ENV["GOODREADS_SECRET"])
        result = client.book_by_isbn(self.isbn)
        self.author = result.authors.first[1].name
        self.title = result.title
        self.cover_art = result.image_url
      end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :books

  # , dependent: destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!

  def index

    if current_user.present?
      @books = User.find(current_user.id).books

    else
      @books = []
    end

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @books }
      end
  end
  
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  def create
    @book = Book.new(params[:book])
    @book.user = current_user

    # if @book.isbn?
    #   # if @book.title == nil || @book.author == nil || @book.avatar == nil
    #   @book.isbn_lookup
    # end

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  
  end

=begin
  1) url.we/path?key=value&key2=value2 ==>> params = {key: value, key2: value2}
  2) url.com/path/with/3 +
      config: match '/path/with/:id'
      ==>> params = {id: 3}
  3) form_for @book do |f| ... end ==>
    params = {book: {hash_of_books_stuff} }
=end

  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json

  # PUT /books/1
  # PUT /books/1.json

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json

  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  def avatar
  
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.haml
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      %h2
        = pluralize(@book.errors.count, "error")
        prohibited this book from being saved:
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br
    = f.text_field :title
  .field
    = f.label :author
    %br
    = f.text_field :author
  .field
    = f.label :isbn
    %br
    = f.text_field :isbn
  .field
    = f.label :avatar
    %br
    = f.file_field :avatar
  .actions
    = f.submit

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book 
|
= link_to 'Back', books_path

app/views/books/index.html.haml
.page-header 
  %h1 Biblio
  =image_tag "/images/library2.jpg"

.navbar
  .navbar-inner
    %a.brand{:href => "#"} Books For DAIZ
    %ul.nav
      %li.active 
        %a{:href => "#"} Home
      %li 
        %a{:href => "#"} Link
      %li 
        %a{:href => "#"} Link
    
%h3= "#{current_user.first_name}'s Collection"

=  link_to 'New Book', new_book_path

%table.table-striped.table-hover
  %tr
    %th Title
    %th Author
    %th ISBN
    %br

  - @books.each do |book| 
    %tr
      %td= book.title 
      %td= book.author 
      %td= book.isbn 
      %td= link_to 'Show', book 
      %td=  link_to 'Edit', edit_book_path(book.id) 
      %td=  link_to 'Destroy', book, method: :delete, data: {confirm: 'Are you sure?' } 

app/views/books/new.html.haml
%h1 New book

= render 'form'

= link_to 'Back', books_path

app/views/books/show.html.haml
%p#notice= notice
%p
  
  / - if @book.avatar#.present?
  = image_tag(@book.avatar_url, :class => "thumb") if @book.avatar.present?
  / - else 
  = image_tag(@book.cover_art) if @book.avatar.present? == false

%p
  %b Title:
  = @book.title
%p
  %b Author:
  = @book.author
%p
  %b Isbn:
  = @book.isbn

= link_to 'Edit', edit_book_path(@book)
|
= link_to 'Back', books_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblio</title>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- <br /> -->

<% if current_user.present? %>
<%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
<% else %>
<%= link_to 'Sign In', new_user_session_path %> |
<%= link_to 'Register', new_user_registration_path %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container"><%= yield %></div>

</body>
</html>